import { Navbar } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import StyledComponentsRegistry from './style-registry'

const inter = Roboto({ weight: '300', subsets: ['greek'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Navbar />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
